name: Paulina Sanpruch - Portfolio
url: http://paulina-sanpruch.github.io
safe: true
lsi: false
pygments: true
markdown: redcarpet
encoding: UTF-8
exclude: ['bootstrap/node_modules', 'node_modules']


